### ISSUE TITLE
Doveauth does not work with Dovecot 2.3.16

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#135]
I have tried deploying to Ubuntu 22.04.3 LTS (instead of Debian 12 like our other Hetzner test setups).
It has `dovecot-core` 2.3.16+dfsg1-3ubuntu2.2

doveauth crashes trying to handle `L` request:
```
Dec 18 15:40:01 c6 doveauth[9258]: WARNING:root:request had no answer: 'H2\t2\t0\t\tauth'
Dec 18 15:40:01 c6 doveauth[9258]: ERROR:root:Exception in the handler
Dec 18 15:40:01 c6 doveauth[9258]: Traceback (most recent call last):
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/local/lib/chatmaild/venv/lib/python3.10/site-packages/chatmaild/doveauth.py", line 146, in handle
Dec 18 15:40:01 c6 doveauth[9258]:     res = handle_dovecot_request(msg, db, config)
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/local/lib/chatmaild/venv/lib/python3.10/site-packages/chatmaild/doveauth.py", line 105, in handle_dovecot_request
Dec 18 15:40:01 c6 doveauth[9258]:     keyname, user = parts[:2]
Dec 18 15:40:01 c6 doveauth[9258]: ValueError: not enough values to unpack (expected 2, got 1)
Dec 18 15:40:01 c6 doveauth[9258]: ----------------------------------------
Dec 18 15:40:01 c6 doveauth[9258]: Exception occurred during processing of request from
Dec 18 15:40:01 c6 doveauth[9258]: Traceback (most recent call last):
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
Dec 18 15:40:01 c6 doveauth[9258]:     self.finish_request(request, client_address)
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
Dec 18 15:40:01 c6 doveauth[9258]:     self.RequestHandlerClass(request, client_address, self)
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
Dec 18 15:40:01 c6 doveauth[9258]:     self.handle()
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/local/lib/chatmaild/venv/lib/python3.10/site-packages/chatmaild/doveauth.py", line 146, in handle
Dec 18 15:40:01 c6 doveauth[9258]:     res = handle_dovecot_request(msg, db, config)
Dec 18 15:40:01 c6 doveauth[9258]:   File "/usr/local/lib/chatmaild/venv/lib/python3.10/site-packages/chatmaild/doveauth.py", line 105, in handle_dovecot_request
Dec 18 15:40:01 c6 doveauth[9258]:     keyname, user = parts[:2]
Dec 18 15:40:01 c6 doveauth[9258]: ValueError: not enough values to unpack (expected 2, got 1)
Dec 18 15:40:01 c6 doveauth[9258]: ----------------------------------------
```

Example request which fails when we try to split on `\t`: `Lshared/passdb/KU(1ujS58<n}/ymgzefb9n@c6.testrun.org`

According to https://doc.dovecot.org/3.0/developer_manual/design/dict_protocol/ "Prior to dovecot 2.3.17 none of the following commands included the username for which the dict operation is performed. Instead, the username from the initial handshake message was used."

So we should either remember the `<user>` part from the `H` message or document that Dovecot < 2.3.17 is not supported.

**Comment by hpk42** [comment]
If it's not too hard with remembering the `<user>` part that it sounds better than spending effort on documenting and having people run into it?
