### ISSUE TITLE
Python 3.9 is not supported

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#191]
Fails with:
```
Traceback (most recent call last):
  File "/usr/local/chatmail/chatmail/venv/bin/cmdeploy", line 5, in <module>
    from cmdeploy.cmdeploy import main
  File "/usr/local/chatmail/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 17, in <module>
    from cmdeploy.dns import show_dns, check_necessary_dns
  File "/usr/local/chatmail/chatmail/cmdeploy/src/cmdeploy/dns.py", line 9, in <module>
    class DNS:
  File "/usr/local/chatmail/chatmail/cmdeploy/src/cmdeploy/dns.py", line 37, in DNS
    def get(self, typ: str, domain: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

We need to test with Python 3.9 or older.

Reported at https://support.delta.chat/t/unable-to-deploy-chatmail/2892/8

**Comment by missytake** [comment]
Tails only ships python3.9, so this is also required to support tails.
